### ISSUE TITLE
Repo takes a long time to clone

### ISSUE THREAD

**Issue by JoshOrndorff** [shawntabrizi/polkadot-launch#15]
Probably because of the binaries in the `bin` directory. I see why they are useful. What about using git lfs?

**Comment by shawntabrizi** [comment]
I don't really see why we would optimize for cloning this project. without including the binaries, users would not really be able to test easily. If it is really a big issue I can remove them, but I have my doubts.

**Comment by JoshOrndorff** [comment]
Would you be interested in a PR that grabs the nodes from published docker images? There could be a default docker images (maybe published by CI in this repo or using the ones from the cumulus workshop) or the user could point to their own docker images in the config file.

**Comment by JoshOrndorff** [comment]
cc @joelamouche

**Comment by shawntabrizi** [comment]
What is the scenario here @JoshOrndorff ?

This is a NodeJS project. It is meant to be installed with NPM and then run using  a local config file. All the things you are describing seem specific to some other use of this project.

**Comment by JoshOrndorff** [comment]
The scenario is that we want to use this tool to start up a network and run integration tests against our parachain. By integration tests I mean start up an actual relay chain and parachain and then use a javascript testing framework to submit transactions and verify expectations.

We already have these integration tests running against a manual-seal-based node because it can easily be started in CI. But our primary product is a parachian, so it would be better to run the integration tests against the parachain. We want to be able to specify the exact version of the relay chain to run.

**Comment by shawntabrizi** [comment]
In my opinion, the right way to do this is to install polkadot launch via NPM as a first step. This is the same as you would do with any utility you want to use in your CI.

**Comment by JoshOrndorff** [comment]
I agree with installing polkadot-launch via npm, and pointing to the parachain node that CI just built. But I don't want to have to compile the parachain each time. I believe that's your exact logic for saying `without including the binaries, users would not really be able to test easily`. I basically agree with you on that. I'm just suggesting that instead of including large platform-specific binaries in this repo, we point to a docker image.

I'm also offering to make a PR for that if you're interested. And it's fine if you're not interested.

**Comment by pepyakin** [comment]
Assuming you have a docker image with the required binaries, why don't you just build a another docker image that layers polkadot-launch with the required paths on top? But then if you can host a docker image, I think it's pretty much a roundabout way to host binary images with a lot of crap that is brought with a docker image. Although I understand that dockerhub provides hosting for your images, I believe that github also provides hosting for them.

So all-in-all I agree with Shawn on this one. I don't think you need to modify polkadot-launch for your use-case. I would recommend against docker. Pointing to a docker image would disrupt non-linux folks out there (they have to run docker within a VM), so I don't think this is a good way to go.

Regarding the original subject however, FWIW, I am also not that keen on keeping the binaries in the repo. I am not sure what users win from that, by launching the most default parachains.

Worth to mention that they do require maintenance, like we have to recompile them every now and then. Also, I feel a bit anxious when I launch some random binary, but perhaps it's just me. (I do understand that I do this all the time, but I guess, most of my software comes from bigger and curated repositories.)
