### ISSUE TITLE
Support parachains

### ISSUE THREAD

**Issue by xlc** [shawntabrizi/polkadot-launch#19]
This doesn't work with our parachains because we have custom types.

Should either have a way to import additional types or avoid using polkadot.js at all.

`api.rpc.system.localPeerId()` and `api.rpc.system.peers()` can be called trivially without polkadot.js

`api.tx.sudo.sudo(api.tx.registrar.registerPara(id, always, wasm, header))` is bit complicated but can just be a flag to disable this and I can do it myself manually.

**Comment by shawntabrizi** [comment]
@xlc the config.json file now has a types section for custom types. let me know if this is not enough.
