### ISSUE TITLE
Supply the `types` with the repo, and allow configs to supply additional/override types

### ISSUE THREAD

**Issue by pepyakin** [shawntabrizi/polkadot-launch#27]

**Comment by bkchr** [comment]
We already merged some types upstream. I think the goal should be to move as much as possible upstream and not track it in here 🙈

**Comment by pepyakin** [comment]
oh good point. Can you show me where is the upstream?

**Comment by shawntabrizi** [comment]
https://github.com/polkadot-js/api/pull/2895 <- here

**Comment by pepyakin** [comment]
Thanks folks, that's the way to go
