### ISSUE TITLE
Support for different relay/parachain types

### ISSUE THREAD

**Issue by crystalin** [shawntabrizi/polkadot-launch#30]
In the case of Moonbeam, we have incompatible types in the relay and the parachain (like the AccountId being H256 in one and H160 in the other). It would be good if we can separate the types to define in the relay and the ones to define for the parachain inside the config file.

**Comment by bkchr** [comment]
AFAIK we only require the types for the relay chain, because we send transactions to the relay chain. But we don't send transactions to the parachain.

**Comment by pepyakin** [comment]
We used to need them to some degree, since we did connect to the cumulus node through ws. Not anymore [though](https://github.com/shawntabrizi/polkadot-launch/commit/2ba06c7626eeeaed0276f1f8cdf81be4ccb0e83e#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L87)

**Comment by crystalin** [comment]
That makes it easier, thanks :)
